about/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('about/', views.about, name='about'),
]

bookSearch/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('bookSearch/', views.bookSearch, name='bookSearch'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from statusToday import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='homepage'),
    path('', include('statusToday.urls')),
    path('', include('about.urls')),
    path('', include('bookSearch.urls')),
    path('', include('user.urls'))
]

statusToday/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('status/', views.status, name='status'),
]

user/urls.py
from django.urls import path, include
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
]

about/models.py
from django.db import models

# Create your models here.

bookSearch/models.py
from django.db import models

# Create your models here.

statusToday/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class statusModel(models.Model):
        status      = models.CharField(max_length = 300)
        time        = models.DateTimeField(default = datetime.now, blank = True)

        def __str__(self):
            return self.status

user/models.py
from django.db import models

# Create your models here.

statusToday/forms.py
from django import forms
from .models import statusModel

class statusForm(forms.ModelForm):
    class Meta:
        model = statusModel
        fields = ['status']
        widget = {
            'status' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'placeholder' : 'What happen today?'
                }
            )
        }

about/views.py
from django.shortcuts import render

# Create your views here.

def about(request):
    return render(request,'about.html')

bookSearch/views.py
from django.shortcuts import render

# Create your views here.

def bookSearch(request):
    return render(request,'bookSearch.html')

project/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

statusToday/views.py
from django.shortcuts import render, redirect

from .models import statusModel
from .forms import statusForm

def status(request):
    status_form = statusForm(request.POST or None)
    all_status = statusModel.objects.all()

    if request.method == 'POST':
        if status_form.is_valid():
            status_form.save()
            return redirect('status')

    context = {
        'status_form' : status_form,
        'all_status' : all_status
    }

    return render(request,'status.html',context)


def homepage(request):
    return render(request, 'homepage.html')


# Create your views here.

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def login_view(request) :
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('homepage')
    else:
        form = AuthenticationForm()
    
    return render(request, 'login.html', {'form': form})

def logout_view(request) :
    if request.method == 'POST':
        logout(request)
        return redirect('homepage')

about/templates/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" 
    content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">    
    <link rel="stylesheet" href="{% static 'css/aboutMe.css' %}">
    

    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->

    <title>About</title>
</head>
<body>
  <div class="theme-switch-wrapper">
    <label class="theme-switch" for="checkbox">
      <input type="checkbox" id="checkbox" />
      <div class="slider round"></div>
    </label>
  </div>
  <div class="aboutMe">
    <dl>
      <dt>Aktivitas saat ini</dt>
      <dd>
        <p>Kuliah</p>
        <p>Tidur</p>
        <p>Yutub</p>
        <p>Ripit</p>
      </dd>
      <dt>Pengalaman Organisasi/Kepanitiaan</dt>
      <dd>
        <h5>Betis 2020</h5>
        <p>VPJ of Akademis dan Pengajar</p>
      </dd>
      <dt>Prestasi</dt>
      <dd>
        <p>Manusia terprocrast sepanjang sejarah</p>
        <p>Pemenang lomba nelen kelereng </p>
      </dd>
    </dl>
  </div>
  <button class="home_button"><a href="{% url 'homepage' %}">Home</a></button>
  

  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/aboutMe.js' %}"></script>
  
</body>
</html>

bookSearch/templates/bookSearch.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">    
    <link rel="stylesheet" href="{% static 'css/bookSearch.css' %}">
    <title>Book Search</title>
</head>
<body>
    <div>
        <h1>Cari Buku</h1>
        <form class="form-inline">
            <input class="inputBook" id="input" type="search" placeholder="Search" aria-label="Search">
            <button id="button" type="submit">Search</button>
        </form>
    </div>
    
    
        <div class="status-container ">
                <table class="table">                    <thead class="table-head">
                    <tr>
                        <th scope="col">Judul</th>
                        <th scope="col">Penulis</th>  
                        <th scope="col">Categories</th>
                        <th scope="col">Sampul</th>
                    </tr>
                </thead>
                <div>
                    <tbody >
                    </tbody>
                </div>
                
            </table>
        </div>

    <div>
        <button class="home_button"><a href="{% url 'homepage' %}">Home</a></button>
    </div>
    
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bookSearch.js' %}"></script>
</body>
</html>

statusToday/templates/homepage.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
{% endblock style %}

{% block judul %} Homepage {% endblock judul %} 

{% block content %}
    <div class="column text-center homepage">
        <h1>HOMEPAGE</h1>
    </div>
    <div class="column text-center button_box">
        <button id="status_butt"><a href="{% url 'status' %}">Status</a></button>
        <button><a href="{% url 'about' %}">About</a></button>
        <button class="home_button"><a href="{% url 'bookSearch' %}">Book Finder</a></button>

    </div>
{% endblock content %}

statusToday/templates/status.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/status.css' %}">
{% endblock style %}

{% block judul %} Status {% endblock judul %} 

{% block content %}
<div class="column text-center">
        <h1>What happen today?</h1>
    </div>
    <div class="column justify-content-center text-center">
        <form method="POST">
            {% csrf_token %}
            <form>
                <!-- <label>{{status_form.staus.label}}</label> -->
                <div id="status">
                    {{status_form.status}}
                </div>
                <button id="tombol" type="Submit" >send</button>
            </form>
        </form>
    </div>

    <div class="column ">
        {% for status in all_status %}
        <div class="row text-center justify-content-center">
            <h4>{{status.status}}</h4>
            <h4>{{status.time}}</h4>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
    {% block style %} {% endblock style%}
    <title>
        {% block judul %} {% endblock judul %}
    </title>


</head>

<body>
        {%if user.is_authenticated %}
        <h4>Welcome, {{ request.user.username }}</h4>
        <form action="{% url 'user:logout'%}" method = "post">
            {%csrf_token%}
            <button type = "submit">Logout</button>
        </form>
        {% else %}
        <button><a href="{% url  'user:login'%}">Login</a></button>
        {% endif %}

    {% block content %} {% endblock content %}
    



</body>

</html>

user/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form action="{%url 'user:login'%}" method = "post">
        {%csrf_token%}
        {{ form }}
        <input type="submit" value="login">
    </form>
</body>
</html>

user/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Logout</title>
</head>
<body>
    <form action="{% url 'logout'%}" method = "post">
        {%csrf_token%}
        <button type = "submit">Logout</button>
    </form>
</body>
</html>